// Template definitions
// Each template defines layout, background, and element scaffolding

export const TEMPLATES = [
  {
    id: 'dark-floral',
    name: 'Dark Floral',
    category: 'Wedding',
    thumbnail: null,
    defaultLayout: 'double',
    background: { type: 'color', value: '#1a2e1a' },
    palette: ['#1a2e1a', '#c9a84c', '#e8f5e8', '#2d4a2d'],
    elements: [
      {
        role: 'bible-verse',
        type: 'text',
        placeholder: 'Genesis 2:18 — "It is not good for man to be alone..."',
        fontFamily: 'Lato',
        fontSize: 9,
        color: '#c9a84c',
        align: 'center',
        position: { x: 0.5, y: 0.06 },
        width: 0.9,
        fontStyle: 'italic',
      },
      {
        role: 'family-intro',
        type: 'text',
        placeholder: 'The family of GAKUTA\n& NTAWANGWANABOSE\ncordially invite you to the wedding of',
        fontFamily: 'Lato',
        fontSize: 10,
        color: '#e8f5e8',
        align: 'center',
        position: { x: 0.5, y: 0.18 },
        width: 0.9,
      },
      {
        role: 'couple-name-1',
        type: 'text',
        placeholder: 'Pascaline',
        fontFamily: 'Great Vibes',
        fontSize: 36,
        color: '#c9a84c',
        align: 'center',
        position: { x: 0.5, y: 0.38 },
        width: 0.9,
      },
      {
        role: 'couple-name-2',
        type: 'text',
        placeholder: '& Audace',
        fontFamily: 'Great Vibes',
        fontSize: 30,
        color: '#e8f5e8',
        align: 'center',
        position: { x: 0.5, y: 0.50 },
        width: 0.9,
      },
      {
        role: 'date',
        type: 'text',
        placeholder: 'Saturday, July 25th 2026',
        fontFamily: 'Lato',
        fontSize: 11,
        color: '#c9a84c',
        align: 'center',
        position: { x: 0.5, y: 0.62 },
        width: 0.9,
        fontWeight: '600',
      },
      {
        role: 'event-1',
        type: 'text',
        placeholder: '09:00 · Introduction & Dowry\nTTC De la Salle Byumba',
        fontFamily: 'Lato',
        fontSize: 9,
        color: '#e8f5e8',
        align: 'center',
        position: { x: 0.5, y: 0.72 },
        width: 0.9,
      },
      {
        role: 'event-2',
        type: 'text',
        placeholder: '13:00 · Religious Ceremony\nByumba Cathedral Parish',
        fontFamily: 'Lato',
        fontSize: 9,
        color: '#e8f5e8',
        align: 'center',
        position: { x: 0.5, y: 0.82 },
        width: 0.9,
      },
      {
        role: 'contacts',
        type: 'text',
        placeholder: 'M.P: 0786792157 · 0732476257\nN.A: 0783621306 · 0784111056',
        fontFamily: 'Lato',
        fontSize: 8,
        color: '#c9a84c',
        align: 'center',
        position: { x: 0.5, y: 0.92 },
        width: 0.9,
      },
    ],
  },

  {
    id: 'minimalist',
    name: 'Minimalist',
    category: 'Wedding',
    thumbnail: null,
    defaultLayout: 'double',
    background: { type: 'color', value: '#faf8f5' },
    palette: ['#faf8f5', '#2c2c2c', '#8b7355', '#d4c5a9'],
    elements: [
      {
        role: 'bible-verse',
        type: 'text',
        placeholder: '"Love is patient, love is kind." — 1 Corinthians 13:4',
        fontFamily: 'Lato',
        fontSize: 8,
        color: '#8b7355',
        align: 'center',
        position: { x: 0.5, y: 0.06 },
        width: 0.85,
        fontStyle: 'italic',
      },
      {
        role: 'family-intro',
        type: 'text',
        placeholder: 'Together with their families',
        fontFamily: 'Lato',
        fontSize: 10,
        color: '#2c2c2c',
        align: 'center',
        position: { x: 0.5, y: 0.20 },
        width: 0.85,
      },
      {
        role: 'couple-name-1',
        type: 'text',
        placeholder: 'Pascaline',
        fontFamily: 'Playfair Display',
        fontSize: 32,
        color: '#2c2c2c',
        align: 'center',
        position: { x: 0.5, y: 0.34 },
        width: 0.9,
      },
      {
        role: 'couple-name-2',
        type: 'text',
        placeholder: '& Audace',
        fontFamily: 'Playfair Display',
        fontSize: 26,
        color: '#8b7355',
        align: 'center',
        position: { x: 0.5, y: 0.48 },
        width: 0.9,
      },
      {
        role: 'date',
        type: 'text',
        placeholder: '25 · 07 · 2026',
        fontFamily: 'Lato',
        fontSize: 13,
        color: '#2c2c2c',
        align: 'center',
        position: { x: 0.5, y: 0.62 },
        width: 0.9,
        fontWeight: '300',
        letterSpacing: '0.2em',
      },
      {
        role: 'event-1',
        type: 'text',
        placeholder: '09:00 AM — Introduction & Dowry\nTTC De la Salle Byumba',
        fontFamily: 'Lato',
        fontSize: 9,
        color: '#2c2c2c',
        align: 'center',
        position: { x: 0.5, y: 0.73 },
        width: 0.85,
      },
      {
        role: 'event-2',
        type: 'text',
        placeholder: '01:00 PM — Church Ceremony\nByumba Cathedral Parish',
        fontFamily: 'Lato',
        fontSize: 9,
        color: '#2c2c2c',
        align: 'center',
        position: { x: 0.5, y: 0.84 },
        width: 0.85,
      },
      {
        role: 'contacts',
        type: 'text',
        placeholder: 'RSVP: 0786792157 · 0783621306',
        fontFamily: 'Lato',
        fontSize: 8,
        color: '#8b7355',
        align: 'center',
        position: { x: 0.5, y: 0.93 },
        width: 0.9,
      },
    ],
  },

  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    category: 'Wedding',
    thumbnail: null,
    defaultLayout: 'single',
    background: { type: 'gradient', value: 'linear-gradient(160deg, #1a1000 0%, #2d1e00 50%, #1a1000 100%)' },
    palette: ['#1a1000', '#c9a84c', '#fff8e7', '#8b6914'],
    elements: [
      {
        role: 'family-intro',
        type: 'text',
        placeholder: 'The Families of\nGAKUTA & NTAWANGWANABOSE\nRequest the honour of your presence',
        fontFamily: 'Lato',
        fontSize: 10,
        color: '#c9a84c',
        align: 'center',
        position: { x: 0.5, y: 0.10 },
        width: 0.88,
      },
      {
        role: 'couple-name-1',
        type: 'text',
        placeholder: 'Pascaline',
        fontFamily: 'Great Vibes',
        fontSize: 44,
        color: '#c9a84c',
        align: 'center',
        position: { x: 0.5, y: 0.33 },
        width: 0.92,
      },
      {
        role: 'couple-name-2',
        type: 'text',
        placeholder: '& Audace',
        fontFamily: 'Great Vibes',
        fontSize: 36,
        color: '#fff8e7',
        align: 'center',
        position: { x: 0.5, y: 0.48 },
        width: 0.92,
      },
      {
        role: 'date',
        type: 'text',
        placeholder: 'Saturday, July 25th 2026',
        fontFamily: 'Playfair Display',
        fontSize: 12,
        color: '#c9a84c',
        align: 'center',
        position: { x: 0.5, y: 0.63 },
        width: 0.9,
        fontStyle: 'italic',
      },
      {
        role: 'event-1',
        type: 'text',
        placeholder: '09:00 AM · TTC De la Salle Byumba',
        fontFamily: 'Lato',
        fontSize: 9,
        color: '#fff8e7',
        align: 'center',
        position: { x: 0.5, y: 0.74 },
        width: 0.88,
      },
      {
        role: 'event-2',
        type: 'text',
        placeholder: '01:00 PM · Byumba Cathedral Parish',
        fontFamily: 'Lato',
        fontSize: 9,
        color: '#fff8e7',
        align: 'center',
        position: { x: 0.5, y: 0.82 },
        width: 0.88,
      },
      {
        role: 'contacts',
        type: 'text',
        placeholder: 'RSVP: 0786792157 · 0783621306',
        fontFamily: 'Lato',
        fontSize: 8,
        color: '#c9a84c',
        align: 'center',
        position: { x: 0.5, y: 0.92 },
        width: 0.9,
      },
    ],
  },
];

export const getTemplate = (id) => TEMPLATES.find(t => t.id === id);
